# Generated by Django 5.1.4 on 2025-01-26 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="코스의 이름", max_length=200)),
                ("description", models.TextField(help_text="코스에 대한 상세 설명")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("python_basics", "Python 기초"),
                            ("data_structures", "자료구조"),
                            ("algorithms", "알고리즘"),
                            ("web_dev", "웹 개발"),
                            ("data_science", "데이터 사이언스"),
                        ],
                        default="python_basics",
                        help_text="코스의 카테고리",
                        max_length=50,
                    ),
                ),
                ("topics", models.JSONField(help_text="JSON 형태의 토픽 목록")),
                (
                    "estimated_hours",
                    models.IntegerField(default=0, help_text="예상 학습 시간(시간)"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="코스 활성화 여부"),
                ),
                (
                    "order",
                    models.IntegerField(default=0, help_text="커리큘럼 내 표시 순서"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("enrolled", "수강중"),
                            ("completed", "완료"),
                            ("dropped", "중단"),
                        ],
                        default="enrolled",
                        help_text="수강 상태",
                        max_length=20,
                    ),
                ),
                ("progress", models.FloatField(default=0, help_text="진행률 (0-100)")),
                (
                    "completed_topics",
                    models.TextField(
                        blank=True, default="", help_text="완료한 토픽 ID (쉼표로 구분)"
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_accessed_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        help_text="수강 중인 코스",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_courses",
                        to="roadmaps.course",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="수강 사용자",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roadmap_enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_accessed_at"],
                "unique_together": {("user", "course")},
            },
        ),
    ]
