# Generated by Django 5.1.4 on 2025-01-26 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roadmaps", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={},
        ),
        migrations.AlterModelOptions(
            name="usercourse",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.RemoveField(
            model_name="course",
            name="category",
        ),
        migrations.RemoveField(
            model_name="course",
            name="estimated_hours",
        ),
        migrations.RemoveField(
            model_name="course",
            name="order",
        ),
        migrations.RemoveField(
            model_name="usercourse",
            name="last_accessed_at",
        ),
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="course",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="course",
            name="topics",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="usercourse",
            name="completed_topics",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="usercourse",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_courses",
                to="roadmaps.course",
            ),
        ),
        migrations.AlterField(
            model_name="usercourse",
            name="progress",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="usercourse",
            name="status",
            field=models.CharField(
                choices=[("enrolled", "수강중"), ("completed", "완료")],
                default="enrolled",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="usercourse",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roadmap_enrollments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
