# Generated by Django 5.1.4 on 2025-01-24 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("roadmaps", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="category",
            field=models.CharField(
                choices=[
                    ("python_basics", "Python 기초"),
                    ("data_structures", "자료구조"),
                    ("algorithms", "알고리즘"),
                    ("web_dev", "웹 개발"),
                    ("data_science", "데이터 사이언스"),
                ],
                default="python_basics",
                help_text="코스의 카테고리",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(help_text="코스에 대한 상세 설명"),
        ),
        migrations.AlterField(
            model_name="course",
            name="estimated_hours",
            field=models.IntegerField(default=0, help_text="예상 학습 시간(시간)"),
        ),
        migrations.AlterField(
            model_name="course",
            name="is_active",
            field=models.BooleanField(default=True, help_text="코스 활성화 여부"),
        ),
        migrations.AlterField(
            model_name="course",
            name="name",
            field=models.CharField(help_text="코스의 이름", max_length=200),
        ),
        migrations.AlterField(
            model_name="course",
            name="order",
            field=models.IntegerField(default=0, help_text="커리큘럼 내 표시 순서"),
        ),
        migrations.AlterField(
            model_name="course",
            name="topics",
            field=models.JSONField(help_text="JSON 형태의 토픽 목록"),
        ),
        migrations.AlterField(
            model_name="usercourse",
            name="completed_topics",
            field=models.TextField(
                blank=True, default="", help_text="완료한 토픽 ID (쉼표로 구분)"
            ),
        ),
        migrations.AlterField(
            model_name="usercourse",
            name="course",
            field=models.ForeignKey(
                help_text="수강 중인 코스",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_courses",
                to="roadmaps.course",
            ),
        ),
        migrations.AlterField(
            model_name="usercourse",
            name="progress",
            field=models.FloatField(default=0, help_text="진행률 (0-100)"),
        ),
        migrations.AlterField(
            model_name="usercourse",
            name="status",
            field=models.CharField(
                choices=[("enrolled", "수강중"), ("completed", "완료"), ("dropped", "중단")],
                default="enrolled",
                help_text="수강 상태",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="usercourse",
            name="user",
            field=models.ForeignKey(
                help_text="수강 사용자",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roadmap_enrollments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
