# Generated by Django 5.1.4 on 2025-01-21 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercourse',
            old_name='created_at',
            new_name='started_at',
        ),
        migrations.RemoveField(
            model_name='course',
            name='difficulty_level',
        ),
        migrations.RemoveField(
            model_name='practiceexercise',
            name='solution_code',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='answer_options',
        ),
        migrations.RemoveField(
            model_name='usercourse',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='usercourse',
            name='enrolled_at',
        ),
        migrations.RemoveField(
            model_name='usercourse',
            name='last_accessed_at',
        ),
        migrations.RemoveField(
            model_name='usercourse',
            name='progress_percentage',
        ),
        migrations.AddField(
            model_name='course',
            name='difficulty',
            field=models.CharField(choices=[('beginner', '입문'), ('intermediate', '중급'), ('advanced', '고급')], default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='estimated_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='choices',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='explanation',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='usercourse',
            name='completed_topics',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='usercourse',
            name='progress',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AlterField(
            model_name='practiceexercise',
            name='initial_code',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='practiceexercise',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lesson'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='correct_answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lesson'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='status',
            field=models.CharField(choices=[('enrolled', '수강 중'), ('completed', '완료'), ('dropped', '중단')], default='enrolled', max_length=20),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to=settings.AUTH_USER_MODEL),
        ),
    ]
