name: codeve CD

on:
  workflow_dispatch:

jobs:
  deploy:
    name: CD Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          key: ${{ secrets.EC2_KEY }}
          host: ${{ secrets.EC2_IP }}
          username: ${{ secrets.EC2_NAME }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            cd ${{ secrets.EC2_PATH }}
            git pull origin develop
            cd ../
            sudo docker compose restart backend
